=== navya-rg/XML/Employees.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="fname" type="xs:string"/>
										<xs:element name="lname" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="dob" type="xs:date"/>
							<xs:element name="age">
								<xs:simpleType>
								    <xs:restriction base="xs:integer">
								      	<xs:minInclusive value="18"/>
								      	<xs:maxInclusive value="65"/>
								    </xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="email">
								<xs:simpleType>
								    <xs:restriction base="xs:string">
								      	<xs:pattern value="[a-z][a-z0-9_\.]*(@)[a-z]*(\.)[a-z]*"/>
								    </xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="mbl">
								<xs:simpleType>
								    <xs:restriction base="xs:string">
								      	<xs:pattern value="[789][0-9]{9}"/>
								    </xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="designation">
								<xs:simpleType>
								    <xs:restriction base="xs:string">
								    	<xs:enumeration value="Intern Consulting"/>
								      	<xs:enumeration value="Java Developer"/>
								      	<xs:enumeration value="Python Developer"/>
								      	<xs:enumeration value="UI/UX Designer"/>
								      	<xs:enumeration value="Database Support"/>
								      	<xs:enumeration value="Technical Consultant"/>
								      	<xs:enumeration value="Senior Technical Consultant"/>
								      	<xs:enumeration value="Lead Technical Consultant"/>
								      	<xs:enumeration value="Branch Manager"/>
								      	<xs:enumeration value="General Manager"/>
								      	<xs:enumeration value="Chief Executive Officer"/>
								  		<xs:enumeration value="Chief Operations Officer"/>
								    </xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="experience">
								<xs:simpleType>
								    <xs:restriction base="xs:decimal">
								      	<xs:minInclusive value="0.0"/>
								    </xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== navya-rg/XML/Employees.xml
<?xml version="1.0"?>
<employees
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="Employees.xsd">
	<employee>
	  <name>
	  	<fname>Jane</fname>
	  	<lname>Doe</lname>
	  </name>
	  <dob>1999-07-19</dob>
	  <age>20</age>
	  <email>jane.doe@xmail.com</email>
	  <mbl>9876543210</mbl>
	  <designation>Java Developer</designation>
	  <experience>3.4</experience>
	</employee>

	<employee>
		<name>
			<fname>John</fname>
			<lname>Smith</lname>
		</name>
		<dob>1994-03-24</dob>
		<age>25</age>
		<email>john.smith@xmail.com</email>
		<mbl>9121212121</mbl>
		<designation>Senior Technical Consultant</designation>
		<experience>6.2</experience>
	</employee>

	<employee>
		<name>
			<fname>Alice</fname>
			<lname>Pinkman</lname>
		</name>
		<dob>1990-08-02</dob>
		<age>33</age>
		<email>alice.pinkman@xmail.com</email>
		<mbl>9898989898</mbl>
		<designation>General Manager</designation>
		<experience>10</experience>
	</employee>

	<employee>
		<name>
			<fname>Bob</fname>
			<lname>Driscol</lname>
		</name>
		<dob>1991-10-16</dob>
		<age>32</age>
		<email>bob.driscol@xmail.com</email>
		<mbl>9999999999</mbl>
		<designation>Chief Executive Officer</designation>
		<experience>9</experience>
	</employee>
</employees>
